api_id = "10170481"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #)<@scaMmEr<
api_hash = "22dd74455eb31c9aca628c3008580142"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               #)sCaMMER^
bot_token = "8433886804:AAFeF9bFZYYg89fosg1Md-tltkjRxX7O2gQ"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #-=(ScAMMeR>
FORCE_CHANNEL = 'ITSGOLU0'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #@_&ScAMmeR#<+
LOGS_CHANNEL = -1002731819287                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #^ScAmmeR%%*
OWNER = 8048202739                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #$^sCAmMer_
image = 'logo.jpg'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #(SCammER-
MONGO_URI = 'mongodb+srv://vikassonawale0:JWyQFas7vlG1bkaL@cluster0.beermge.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #<##sCAMmer$)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #<##sCAMmer$)
name = 'saksham'
OWNER_USERNAME = 'ITSGOLU1'

START_TEXT="""
I'm Batch-Txt Extractor bot....!

🚀 Made By @Kingextractor🚀

Usage : First select the app listed below. ⤵️
"""
START_TEXT1="""
I'm Batch-Txt Extractor bot....!

🎯 Made By @sakshambhaiya 🎯
🔰  Now, select the course listed below. 📌
"""
START_TEXTCP="""
I'm CLASSPLUS Extractor bot....!

⤵️  Now, select the Option listed below. 🎯
"""
START_TEXTAPPX="""
I'm APPX Extractor bot....!

🔰  Now, select the Option listed below. 🎯
"""
START_TEXTCP1="""
I'm Going to Generate Auth Token....!

🎯  Now, select the Methods to Geneterate Classplus Auth Token. ✅
"""
HELP_TEXT="""
I'm Batch extractor bot...!
🚀Commands

/helper - For Extracting Txts.

⚠️ Save this id » @sakshambhaiya in case of Copyright infringement.
"""
